require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AvailableBoardgamesController do

  # This should return the minimal set of attributes required to create a valid
  # AvailableBoardgame. As you add validations to AvailableBoardgame, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all available_boardgames as @available_boardgames" do
      available_boardgame = AvailableBoardgame.create! valid_attributes
      get :index
      assigns(:available_boardgames).should eq([available_boardgame])
    end
  end

  describe "GET show" do
    it "assigns the requested available_boardgame as @available_boardgame" do
      available_boardgame = AvailableBoardgame.create! valid_attributes
      get :show, :id => available_boardgame.id
      assigns(:available_boardgame).should eq(available_boardgame)
    end
  end

  describe "GET new" do
    it "assigns a new available_boardgame as @available_boardgame" do
      get :new
      assigns(:available_boardgame).should be_a_new(AvailableBoardgame)
    end
  end

  describe "GET edit" do
    it "assigns the requested available_boardgame as @available_boardgame" do
      available_boardgame = AvailableBoardgame.create! valid_attributes
      get :edit, :id => available_boardgame.id
      assigns(:available_boardgame).should eq(available_boardgame)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AvailableBoardgame" do
        expect {
          post :create, :available_boardgame => valid_attributes
        }.to change(AvailableBoardgame, :count).by(1)
      end

      it "assigns a newly created available_boardgame as @available_boardgame" do
        post :create, :available_boardgame => valid_attributes
        assigns(:available_boardgame).should be_a(AvailableBoardgame)
        assigns(:available_boardgame).should be_persisted
      end

      it "redirects to the created available_boardgame" do
        post :create, :available_boardgame => valid_attributes
        response.should redirect_to(AvailableBoardgame.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved available_boardgame as @available_boardgame" do
        # Trigger the behavior that occurs when invalid params are submitted
        AvailableBoardgame.any_instance.stub(:save).and_return(false)
        post :create, :available_boardgame => {}
        assigns(:available_boardgame).should be_a_new(AvailableBoardgame)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AvailableBoardgame.any_instance.stub(:save).and_return(false)
        post :create, :available_boardgame => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested available_boardgame" do
        available_boardgame = AvailableBoardgame.create! valid_attributes
        # Assuming there are no other available_boardgames in the database, this
        # specifies that the AvailableBoardgame created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AvailableBoardgame.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => available_boardgame.id, :available_boardgame => {'these' => 'params'}
      end

      it "assigns the requested available_boardgame as @available_boardgame" do
        available_boardgame = AvailableBoardgame.create! valid_attributes
        put :update, :id => available_boardgame.id, :available_boardgame => valid_attributes
        assigns(:available_boardgame).should eq(available_boardgame)
      end

      it "redirects to the available_boardgame" do
        available_boardgame = AvailableBoardgame.create! valid_attributes
        put :update, :id => available_boardgame.id, :available_boardgame => valid_attributes
        response.should redirect_to(available_boardgame)
      end
    end

    describe "with invalid params" do
      it "assigns the available_boardgame as @available_boardgame" do
        available_boardgame = AvailableBoardgame.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AvailableBoardgame.any_instance.stub(:save).and_return(false)
        put :update, :id => available_boardgame.id, :available_boardgame => {}
        assigns(:available_boardgame).should eq(available_boardgame)
      end

      it "re-renders the 'edit' template" do
        available_boardgame = AvailableBoardgame.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AvailableBoardgame.any_instance.stub(:save).and_return(false)
        put :update, :id => available_boardgame.id, :available_boardgame => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested available_boardgame" do
      available_boardgame = AvailableBoardgame.create! valid_attributes
      expect {
        delete :destroy, :id => available_boardgame.id
      }.to change(AvailableBoardgame, :count).by(-1)
    end

    it "redirects to the available_boardgames list" do
      available_boardgame = AvailableBoardgame.create! valid_attributes
      delete :destroy, :id => available_boardgame.id
      response.should redirect_to(available_boardgames_url)
    end
  end

end
