require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProposedVenuesController do

  # This should return the minimal set of attributes required to create a valid
  # ProposedVenue. As you add validations to ProposedVenue, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all proposed_venues as @proposed_venues" do
      proposed_venue = ProposedVenue.create! valid_attributes
      get :index
      assigns(:proposed_venues).should eq([proposed_venue])
    end
  end

  describe "GET show" do
    it "assigns the requested proposed_venue as @proposed_venue" do
      proposed_venue = ProposedVenue.create! valid_attributes
      get :show, :id => proposed_venue.id
      assigns(:proposed_venue).should eq(proposed_venue)
    end
  end

  describe "GET new" do
    it "assigns a new proposed_venue as @proposed_venue" do
      get :new
      assigns(:proposed_venue).should be_a_new(ProposedVenue)
    end
  end

  describe "GET edit" do
    it "assigns the requested proposed_venue as @proposed_venue" do
      proposed_venue = ProposedVenue.create! valid_attributes
      get :edit, :id => proposed_venue.id
      assigns(:proposed_venue).should eq(proposed_venue)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProposedVenue" do
        expect {
          post :create, :proposed_venue => valid_attributes
        }.to change(ProposedVenue, :count).by(1)
      end

      it "assigns a newly created proposed_venue as @proposed_venue" do
        post :create, :proposed_venue => valid_attributes
        assigns(:proposed_venue).should be_a(ProposedVenue)
        assigns(:proposed_venue).should be_persisted
      end

      it "redirects to the created proposed_venue" do
        post :create, :proposed_venue => valid_attributes
        response.should redirect_to(ProposedVenue.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved proposed_venue as @proposed_venue" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProposedVenue.any_instance.stub(:save).and_return(false)
        post :create, :proposed_venue => {}
        assigns(:proposed_venue).should be_a_new(ProposedVenue)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProposedVenue.any_instance.stub(:save).and_return(false)
        post :create, :proposed_venue => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested proposed_venue" do
        proposed_venue = ProposedVenue.create! valid_attributes
        # Assuming there are no other proposed_venues in the database, this
        # specifies that the ProposedVenue created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProposedVenue.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => proposed_venue.id, :proposed_venue => {'these' => 'params'}
      end

      it "assigns the requested proposed_venue as @proposed_venue" do
        proposed_venue = ProposedVenue.create! valid_attributes
        put :update, :id => proposed_venue.id, :proposed_venue => valid_attributes
        assigns(:proposed_venue).should eq(proposed_venue)
      end

      it "redirects to the proposed_venue" do
        proposed_venue = ProposedVenue.create! valid_attributes
        put :update, :id => proposed_venue.id, :proposed_venue => valid_attributes
        response.should redirect_to(proposed_venue)
      end
    end

    describe "with invalid params" do
      it "assigns the proposed_venue as @proposed_venue" do
        proposed_venue = ProposedVenue.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProposedVenue.any_instance.stub(:save).and_return(false)
        put :update, :id => proposed_venue.id, :proposed_venue => {}
        assigns(:proposed_venue).should eq(proposed_venue)
      end

      it "re-renders the 'edit' template" do
        proposed_venue = ProposedVenue.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProposedVenue.any_instance.stub(:save).and_return(false)
        put :update, :id => proposed_venue.id, :proposed_venue => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested proposed_venue" do
      proposed_venue = ProposedVenue.create! valid_attributes
      expect {
        delete :destroy, :id => proposed_venue.id
      }.to change(ProposedVenue, :count).by(-1)
    end

    it "redirects to the proposed_venues list" do
      proposed_venue = ProposedVenue.create! valid_attributes
      delete :destroy, :id => proposed_venue.id
      response.should redirect_to(proposed_venues_url)
    end
  end

end
